# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79eda95cbd79b5ca299b937f62b53d85b302d257d0913c25d1987067069bd136159a9e3b5160c3eaa8e8ea695120edf1f010734c4f0dab140c2a7a380dcb43d4

test:
  secret_key_base: a932bd625b620adb256dbe300190b4de64a6a4a03fa8956a2ba81a1502d68ef4802d66b943aece415150d13435c72fd95e993434fad4b0bafaf6eb2d0f4f448a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
